# para correr -> docker compose up --build

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    expose:
#      - "3000"
#      - "54322"
    network_mode: host # Resolverlo de otra forma
#    platform: linux/amd64
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:4.4.6
    command: mongod --quiet --logpath /dev/null # No mostrar logs
#    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: