create table "public"."employees" (
    "id" bigint generated always as identity not null,
    "name" text,
    "email" text,
    "created_at" timestamp with time zone default now()
);


create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX employees_pkey ON public.employees USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."employees" add constraint "employees_pkey" PRIMARY KEY using index "employees_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";


