create table "public"."album" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text default ''::text,
    "org_id" bigint not null
);


alter table "public"."album" enable row level security;

alter table "public"."songs" add column "album_id" bigint;

CREATE UNIQUE INDEX album_id_key ON public.album USING btree (id);

CREATE UNIQUE INDEX album_pkey ON public.album USING btree (id);

alter table "public"."album" add constraint "album_pkey" PRIMARY KEY using index "album_pkey";

alter table "public"."album" add constraint "album_org_id_fkey" FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE not valid;

alter table "public"."album" validate constraint "album_org_id_fkey";

alter table "public"."songs" add constraint "songs_album_id_fkey" FOREIGN KEY (album_id) REFERENCES album(id) ON DELETE CASCADE not valid;

alter table "public"."songs" validate constraint "songs_album_id_fkey";


