create table "public"."members" (
    "user" bigint not null,
    "org" bigint not null
);


alter table "public"."members" enable row level security;

create table "public"."organizations" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null default ''::character varying,
    "image" character varying
);


alter table "public"."organizations" enable row level security;

alter table "public"."songs" drop column "author";

alter table "public"."songs" add column "org" bigint not null;

alter table "public"."songs" alter column "id" drop default;

alter table "public"."songs" alter column "id" add generated by default as identity;

CREATE UNIQUE INDEX members_pkey ON public.members USING btree ("user", org);

CREATE UNIQUE INDEX organizations_id_key ON public.organizations USING btree (id);

CREATE UNIQUE INDEX organizations_pkey ON public.organizations USING btree (id);

CREATE UNIQUE INDEX songs_id_key ON public.songs USING btree (id);

CREATE UNIQUE INDEX songs_pkey ON public.songs USING btree (id);

alter table "public"."members" add constraint "members_pkey" PRIMARY KEY using index "members_pkey";

alter table "public"."organizations" add constraint "organizations_pkey" PRIMARY KEY using index "organizations_pkey";

alter table "public"."songs" add constraint "songs_pkey" PRIMARY KEY using index "songs_pkey";

alter table "public"."members" add constraint "members_org_fkey" FOREIGN KEY (org) REFERENCES organizations(id) ON DELETE CASCADE not valid;

alter table "public"."members" validate constraint "members_org_fkey";

alter table "public"."members" add constraint "members_user_fkey" FOREIGN KEY ("user") REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."members" validate constraint "members_user_fkey";

alter table "public"."organizations" add constraint "organizations_id_key" UNIQUE using index "organizations_id_key";

alter table "public"."songs" add constraint "songs_id_key" UNIQUE using index "songs_id_key";

alter table "public"."songs" add constraint "songs_org_fkey" FOREIGN KEY (org) REFERENCES organizations(id) ON DELETE CASCADE not valid;

alter table "public"."songs" validate constraint "songs_org_fkey";


