alter table "public"."album" drop constraint "album_id_key";

alter table "public"."album" drop constraint "album_org_id_fkey";

alter table "public"."songs" drop constraint "songs_album_id_fkey";

alter table "public"."album" drop constraint "album_pkey";

drop index if exists "public"."album_id_key";

drop index if exists "public"."album_pkey";

drop table "public"."album";

create table "public"."albums" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text default ''::text,
    "org" bigint not null
);


alter table "public"."albums" enable row level security;

alter table "public"."songs" drop column "album_id";

alter table "public"."songs" add column "album" bigint;

CREATE UNIQUE INDEX album_id_key ON public.albums USING btree (id);

CREATE UNIQUE INDEX album_pkey ON public.albums USING btree (id);

alter table "public"."albums" add constraint "album_pkey" PRIMARY KEY using index "album_pkey";

alter table "public"."albums" add constraint "album_id_key" UNIQUE using index "album_id_key";

alter table "public"."albums" add constraint "albums_org_fkey" FOREIGN KEY (org) REFERENCES organizations(id) ON DELETE CASCADE not valid;

alter table "public"."albums" validate constraint "albums_org_fkey";

alter table "public"."songs" add constraint "songs_album_fkey" FOREIGN KEY (album) REFERENCES albums(id) ON DELETE CASCADE not valid;

alter table "public"."songs" validate constraint "songs_album_fkey";


