name: Deploy the aplication (ah re que ahora no hago nada)
on: 
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  exploring:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - run: echo "my workflow"
      - run: ls
      - run: cd harmony-backend && ls
      - run: cd harmony-frontend && ls
