name: Test frontend of pull request
on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Move to front
        run: cd harmony-frontend
      - name: Install modules
        run: npm install
      - name: Run test
        run: npm run test
  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repo
  #       uses: actions/checkout@v3
  #     - name: Move to front
  #       run: cd harmony-frontend
  #     - name: Install modules
  #       run: npm install
  #     - name: Run coverage
  #       run: npm run coverage
